### ISSUE TITLE
UPDATE tampilan home

### ISSUE THREAD

**Issue by Mroismaulana** [Mroismaulana/WebsiteProfile#8]
jadi di tampilan paling atas itu gambar yang bisa di auto slide dan dibawanya ada beberapa kata selamat datang dll dan di iringi beberapa gambar atau penghargaan dan terakri ada kata penutup dan yang bisa admin nanti di usahakan bisa mengisi atau mengubah tampilan tersebut dari fitur admin bukan dicoding ulang (skema gambar akan saya kirim ke @maul-lq )

**Comment by maul-lq** [comment]
@Mroismaulana gambarnya apa saja buat di menu branda?
